module.exports = {
    // SERVER_URL : "http://api2.foodilog.com",
    SERVER_URL: 'http://162.243.212.155',
    SERVICE_PORT : ":80",

    FB_LOGIN_URL: "/v1/login/facebook",
    GOOGLE_LOGIN_URL: "/v1/login/google",
    TWITTER_LOGIN_URL: "/v1/login/twitter",
    GET_PROFILE_URL: "/v1/profile/",
    UPDATE_MY_PROFILE: "/v1/user/me",
    //private let HEAD_ICON_URL: String           = "/v1/user/picture"
    HEAD_ICON_URL: "/v1/picture",
    HEAD_ICON_RES_URL: "/v1/resource/",
    CREATE_LOG_URL: "/v1/flog/create",
    UPDATE_LOG_URL: "/v1/flog/",
    GET_MY_COUNTS_URL: "/v1/count",
    GET_FOLLOWABLE_LIST: "/v1/followable",
    FOLLOW_URL: "/v1/follow/list",
    UNFOLLOW_URL: "/v1/follow",
    GET_RESTAURANT_URL: "/v1/restaurant/",
    GET_FOLLOW_URL: "/v1/follow/list",
    GET_FOLLOWME_URL: "/v1/followme/list",
    GET_LOGLIST_URL: "/v1/floglist/user/",
    GET_LOGDETAIL_URL: "/v1/flog/",
    CREATE_DISH_URL: "/v1/flog/%@/dish/create",
    DELETE_DISH_URL: "/v1/flog/%@/dish/%@",
    UPDATE_DISH_URL: "/v1/flog/%@/dish/%@",
    LOG_UPLOAD_PHOTO_URL: "/v1/flog/%@/photo/create",
    DELETE_LOG_PHOTO_URL: "/v1/flog/%@/photo/%@",
    // private let GET_LOG_COMMENTS_RUL: "/v1/comment/all/",
    GET_LOG_COMMENTS_RUL: "/v1/flog/%@/comment",
    // private let COMMENT_LOG_URL: "/v1/comment/create",
    COMMENT_LOG_URL: "/v1/comment",
    FAVOURATE_URL: "/v1/favourate/",
    GET_MESSAGES_URL: "/v1/messages",
    SEARCH_URL: "/v1/search",
    COMPLAIN_URL: "/v1/complain",
    SEARCH_IN_RESULT_URL: "/v1/searchresult",
    GET_MENU_URL: "/v1/menu/",
    // GET_FAVOURATE_URL: "/v1/favourate/%@/%@",
    GET_RESTAURANT_LOGLIST_URL: "/v1/floglist/restaurant/",
    GET_DISH_LOGLIST_URL: "/v1/floglist/dish/",
    // GET_DISH_DETAIL_URL: String     = "/v1/flog/%@/dish/%@",  //log dish
    GET_DISH_URL: "/v1/dish/",
    SEARCH_USER_URL: "/v1/usersearch",
    NEW_DISH_URL: "/v1/dish/create",
    LOG_LIKE_URL: "/v1/floglike/",
    MUST_TRY_URL: "/v1/musttry/",
    PHOTOS_URL: "/v1/photos/",
    // SNS_SYNC_URL: "/v1/publish/%@/%@",
    GOOGLE_IOS_CLIENTID: "GOOGLE_IOS_CLIENTID",
    TWITTER_CONSUMER_KEY: "TWITTER_CONSUMER_KEY",
    TWITTER_CONSUMER_SECRET: "TWITTER_CONSUMER_SECRET",
    APP_VERSION: "1.0.0"
}