
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foodilog' do
  use_frameworks!
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'BatchedBridge',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'Google/SignIn'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

end

