export type RestaurantInfo = {
    id: string,
    name: string,
    type: string,
    star: number,
    address: string,
    photoUrl: string,
    photoUrlPrefix: string,
    photoUrlSuffix: string,
    distance: number,
    favourate: false,
    photoId: number,
    priceTier: string,
    rating: number,
    likes: number,
    hasMenu: false,
    isOpen: false,
    tel: string,
    open: string,
    logCount: number,
    dishCount: number,
    coordinate:[],
    lat:string,
    lng: string,
}